site_name: Método RK4

theme:
  name: "material"


nav:
  - "Inicio": index.md
  - "Explicación del método implementado": explanation.md
  - "Tutorial": tutorials.md
  - "Referencia": reference.md

plugins:
  - mkdocstrings

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js


